---
apiVersion: v1
kind: Pod

metadata:
  name: nginx-limit
  namespace: dev

spec:
  containers:
    - name: nginx
      image: nginx:latest

      resources:
        requests:
          cpu: "250m"
          memory: "128Mi"

        limits:
          cpu: "500m"
          memory: "256Mi"
