---
apiVersion: v1

kind: PersistentVolume

metadata:
  name: demo-pv

spec:
  storageClassName: ""

  capacity:
    storage: 1Gi

  accessModes:
    - ReadWriteOnce

  hostPath:
    path: /home/yasmin/hostpath-demo
