---
apiVersion: apps/v1

kind: Deployment

metadata:
  name: flask-liveness

spec:
  replicas: 1

  selector:
    matchLabels:
      app: flask-liveness

  template:
    metadata:
      labels:
        app: flask-liveness

    spec:
      containers:
        - name: flask-app
          image: yasmin478/flask-liveness:v1

          ports:
            - containerPort: 5000

          livenessProbe:
            httpGet:
              path: /health
              port: 5000

            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
