name: Kubernetes manifest validation workflow

on:
  push:
    branches:
      - main

    paths:
      - 'kubernetes/**'
      - '.github/workflows/k8s.yml'

jobs:
  validate-kubernetes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show Kubernetes directory structure
        run: ls -R kubernetes

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Validate Kubernetes manifest files
        run: |
          find kubernetes -type f \( -name "*.yaml" -o -name "*.yml" \) | while read -r file; do
            echo "Validating $file"
            kubectl apply --dry-run=client -f "$file"
          done